### ISSUE TITLE
Future Development Suggestions: Replay/Forward Options (Outgoing Emails using PHPMail/SMTP)

### ISSUE THREAD

**Issue by ahmednitul** [synox/disposable-mailbox#10]
first of all, thanks to everyone behind the development of this awesome scripts.

i would like to suggest a function for future development.

it would be very nice if you can add "replay/forward" functions to the script, so users would be able to response to the arrived mails directly from the app, may use "PHP Mail" and/or "SMTP" protocol for outbound mails.

**Comment by synox** [comment]
Sounds useful. I'm a bit worried about abuse  - what if hackers are using it to send spam? 


You could enforce the TO and FROM, which could limit the abuse potential. (Howevery, I could still send a forged mail to the service, and then reply to a random address. )

An suggestions how to implement it?

**Comment by ahmednitul** [comment]
Hi there,

Yes- I think spam/abuse would be a huge headache for sites with good amounts of traffic, to avoid that you may introduce "captcha" (using solvemedia or re-captcha api) to comply verification when someone clicks "replay" or "forward" button (for outbound mails only)

I have an idea about releasing your app's improved version with monetization support with some quick tweaking to add some awesome functions like: multiple domains support, auto forwarding (premium function that can be enabled by completing cpa actions so the webmaster do gets paid for it) and push-notification using third party services, secure-locking (able to set a permanent password to reserve the email address permanently, viewable only using the permanent password)

If you are interested, we can work together to develop and release this commercial version, I know some peoples who would be gladly purchase the licensed copy for a minimal fee's but by selling multiple quantity it is possible to fundraise approximately $1000-2500 USD to recover the development hours costs.

Do let me know if you are interested, if not then its okay :) thank you so much for creating the base, I'll do workaround it.

**Comment by synox** [comment]
Thanks for the offer. I don't see any commercial potential and a to proved everything opensource. 

There are other better alternatives out there (see https://mailsac.com/). This project is about simplicity, as few lines of code as possible. 

Contributions for reply features are welcome.
