### ISSUE TITLE
Error when deploy in heroku

### ISSUE THREAD

**Issue by HmmmmInc** [synox/disposable-mailbox#104]
I have a 403 Forbidden error when deploy your repo to Heroku.

**Comment by ParveenBhadooOfficial** [comment]
It's not directly deployable to Heroku. Because the files are in src folder, also you still need a catch-all account and have to setup config.php in your repo. I'll update heroku direct deployment at github.com/bhadoomail/bhadoomail shortly.

**Comment by HmmmmInc** [comment]
Hope it will be released soon <3
