### ISSUE TITLE
IMAP sever configuration 

### ISSUE THREAD

**Issue by wmantly** [synox/disposable-mailbox#14]
I am trying to set this project up on Ubuntu 16.04 container. I am running into some issues setting up the IMAP server. If i can get some guidance on how and what IMAP server you or others who have set this up with, that would be great.

What OS do you have this set up on? 
What IMAP server do you use?
What configuration does the IMAP server have?

**Comment by synox** [comment]
It should work on any standard imap server. 

For testing I used  ubuntu with dovecot:

+        sudo mkdir /home/vagrant/Maildir
+        sudo chown -R vagrant:vagrant /home/vagrant/Maildir
+        sudo chmod a+rw /home/vagrant/Maildir

+        echo 'Installing Dovecot'
+        sudo apt-get -qq -y install dovecot-imapd
+        sudo touch /etc/dovecot/local.conf
+        sudo chmod go+rw /etc/dovecot/local.conf
+        echo 'mail_location = maildir:/home/vagrant/Maildir' >> /etc/dovecot/local.conf
+        echo 'disable_plaintext_auth = no' >> /etc/dovecot/local.conf
+        echo 'mail_max_userip_connections = 10000' >> /etc/dovecot/local.conf
+        sudo restart dovecot

**Comment by synox** [comment]
see also #3 and #9 
let me know if it works.

**Comment by synox** [comment]
did it work for you?

**Comment by synox** [comment]
You should find all the flags on http://php.net/manual/en/function.imap-open.php

example for gmail: http://stackoverflow.com/a/32224399/79461
