### ISSUE TITLE
Created everything what to do now to get it worked?

### ISSUE THREAD

**Issue by parveenbhadoo** [synox/disposable-mailbox#15]
check at http://139.59.58.223

**Comment by synox** [comment]
check your php error logs

**Comment by parveenbhadoo** [comment]
how to set imap settings in dns settings and config.php file

**Comment by synox** [comment]
you need a catch-all email account, and the configure the correct imap account. what does your error log say?

**Comment by parveenbhadoo** [comment]
i have a account that catches all emails. but i don't know what to fill in config.php file
the host name
the domainhost name
these are two things i m unable to understand

**Comment by synox** [comment]
here is an example: 
```
$config['imap']['url'] = '{imap.supermail.com/imap/ssl}INBOX';
$config['imap']['username'] = "fs902jfl";
$config['imap']['password'] = "happy-puppy-53";

// email domain, usually different from imap hostname:
$config['mailHostname'] = "supermail.com";
```

does that help? tell me which description would have helped you more.

**Comment by parveenbhadoo** [comment]
i don't know where is the problem, login with putty at 139.59.58.223 and user= root password= katehra@1
it is a free server so no problem displaying key here, please tell me where is the problem.

**Comment by synox** [comment]
I don't know how to setup a webserver or an IMAP server. You should learn to to that - in order to keep the server running and safe. Otherwise, it's maybe better to use a shared hoster with webspace and imap, i can get that starting from 1$/month. 

You may reopen this issue by providing detailed errors logs.
