### ISSUE TITLE
Not receiving Mails

### ISSUE THREAD

**Issue by ArtCore7** [synox/disposable-mailbox#17]
Hi synox,

I don't receive any mails on your script, i think i configured the config.php correctly but still can receive any mails.

My Settings:
```
$config['imap']['url'] = '{***.com:993/imap/ssl/novalidate-cert}INBOX';
$config['imap']['username'] = "xUsername";
$config['imap']['password'] = "xPassword";
```

If i try to run this test.php:
```
<?php
$mbox = imap_open("{***.com:993/imap/ssl/novalidate-cert}", "xUsername", "xPassword");

echo "<h1>Mailboxes</h1>\n";
$folders = imap_listmailbox($mbox, "{***.com:993/imap/ssl/novalidate-cert}", "*");

if ($folders == false) {
    echo "Call failed<br />\n";
} else {
    foreach ($folders as $val) {
        echo $val . "<br />\n";
    }
}

echo "<h1>Headers in INBOX</h1>\n";
$headers = imap_headers($mbox);

if ($headers == false) {
    echo "Call failed<br />\n";
} else {
    foreach ($headers as $val) {
        echo $val . "<br />\n";
    }
}

imap_close($mbox);
?>
```

i get the following page

> Mailboxes
> 
> {***.com:993/imap/ssl/novalidate-cert}Papierkorb
> {***.com:993/imap/ssl/novalidate-cert}Archiv
> {***.com:993/imap/ssl/novalidate-cert}Entw&APw-rfe
> {***.com:993/imap/ssl/novalidate-cert}Spam
> {***.com:993/imap/ssl/novalidate-cert}Gesendet
> {***.com:993/imap/ssl/novalidate-cert}INBOX
> Headers in INBOX
> 
> Call failed

So i think the config.php is right, because i use the same configuration and the INBOX folder is on the imap server

**Comment by ArtCore7** [comment]
Error when sending Mail from an gmail Account:

```
Die Antwort vom Remoteserver ist:
550 5.1.1 <test@****.com>: Recipient address rejected: User unknown in virtual alias table


Final-Recipient: rfc822; test@****.com
Action: failed
Status: 5.1.1
Remote-MTA: dns; ***.com. (85.*.*.*, the server for the domain ****.com.)
Diagnostic-Code: smtp; 550 5.1.1 <test@****.com>: Recipient address rejected: User unknown in virtual alias table
Last-Attempt-Date: Thu, 23 Mar 2017 10:39:09 -0700 (PDT)
```

**Comment by ArtCore7** [comment]
**_Okay please close the Issue, i am to dumb to read correctly:_**

- IMAP account and a domain **with catch-all configuration.** (all mails go to one mailbox).

**Comment by synox** [comment]
Yeah it doesn't do that magic (yet). I adjusted to title to make it more clear.

**Comment by ArtCore7** [comment]
Thanks for the fast respone... now with the Catch All Mail Account it is working perfectly, now i just need another domain to run my own GuerrillaMail.

Nice work - Love this script!
