### ISSUE TITLE
Visual issues on FireFox

### ISSUE THREAD

**Issue by Spegeli** [synox/disposable-mailbox#19]
In FireFox it seems there are some Visual issues: http://i.epvpimg.com/UY9Meab.png
(Left FireFox, Right IE10)

**Comment by synox** [comment]
You are saying in firefox on windows the content is showed in the middle of the screen instead of the top?

**Comment by synox** [comment]
I can't reproduce it. Which version and OS?

**Comment by Spegeli** [comment]
Windows 10 and i use the latest GitHub Version.

Here you can see it: https://trashmail.spegeli.de/

**Comment by synox** [comment]
duplicates  #20
