### ISSUE TITLE
Support multiple domains for address generation and reading mails

### ISSUE THREAD

**Issue by himsingh17** [synox/disposable-mailbox#21]
Hello Dev,

Is there any way to add more domains under this script ?
and show random domain emails ?

Thank you

**Comment by synox** [comment]
This is currently not supported, but could be implemented. Would you store are mails for all domains in one mailbox?

**Comment by himsingh17** [comment]
I will store all emails for all domains in one mailbox or it may be connected in background !!

**Comment by synox** [comment]
Can be done with only a few changes. You can create a pull request or wait until somebody has free weekend. ;-)

**Comment by himsingh17** [comment]
I hope you will have some free time in near future 😃. 
Please do those required changes.
Thanks a lot

**Comment by synox** [comment]
Will you create a public or private instance? Would be great to have a public "demo".

**Comment by himsingh17** [comment]
I will create Public one.

**Comment by synox** [comment]
please test https://github.com/synox/disposable-mailbox/tree/feature/multi-domain

**Comment by himsingh17** [comment]
It's not working !!
Emails sent to a domain email whose IMAP credentials were entered in config are only showing in disposable email.
For example - The Domain with IMAP setting is "example.com"  and additional domains are "example.xyz".

So, Emails sent to example@example.com are showing up but Emails sent to example@example.xyz are not showing up in disposable email.

**Comment by synox** [comment]
What happens when you swap the order on the config file? 

    $config['public']['domains'] = array("example.xyz", "example.com");

**Comment by parveenbhadoo** [comment]
@synox  please update when it starts working i would like to update in on site https://www.emailbygmail.com

**Comment by synox** [comment]
maybe add an option for the user to manually select the domai.

**Comment by SmugZombie** [comment]
This may not fix their issues, however I have been able to use multiple domains successfully using:

$config['mailHostname'] = $_SERVER['SERVER_NAME']; 

This allows me to point multiple domains to the same web root.  Such as example.com and example.net point to the same webroot but act as seperate websites as only example.com can read test@example.com and example.net can only read test@example.net.

**Comment by Spegeli** [comment]
Is this feature already included in the latest master branch?

**Comment by HashHackerAds** [comment]
Someone made a Good Multiple Working Email Site using this. here at https://email.bhadoo.net
i think we can read gmail, yahoo mail etc. by forwarding them to their email address.

**Comment by HashHackerAds** [comment]
Is there any update when multi domain support will be available? or any updates on project?

**Comment by synox** [comment]
There are currently no plans. Contributions are welcome.

**Comment by synox** [comment]
@HashHackerAds Please test branch https://github.com/synox/disposable-mailbox/tree/vanilla_php

**Comment by synox** [comment]
@Spegeli you have a nice design! Can you share the code for the line "Du hast 2 Nachrichten in deinem Postfach"? I might include it... :) 

how to configure multiple domains? see https://github.com/synox/disposable-mailbox/blob/master/src/config.sample.php

(if you put only one domain in the array, the interface it still kind of ugly...)

I fixed the reload problem (commented 'reloadWithTurbolinks') and merged to master. please pull and test again.

**Comment by Spegeli** [comment]
@synox ok auto refresh is not working on vanilla build.
and i know how to setup the domains, but how to setup the email configs self? because we insert only 1 catch-all mailbox? so how to get access to the 2nd catch-all from the other domain?

**Comment by synox** [comment]
ah! My assumption is that you send all your mails to one inbox. 
Domains: *@example.com, *@example.org
Redirect to inbox: catch-all-asdf73623@mytech.com

On my webhoster i can define to forward mails of multiple domains to the same inbox. Otherwise you would have to forward them all to the same inbox. 

Another way would be fetching from different imap accounts, but that would only complicate and slow down things, imho.

**Comment by synox** [comment]
I think bhadoomail also works with only one inbox for all domains, right? (https://bhadoomail.com/forwarding/)

**Comment by HashHackerAds** [comment]
@synox @Spegeli 
I have forwarded all email domains to one domain.
I am hosting the email of all those domains in one place whereas the websites are hosted at different places and are of different people.
By this it doesn't effects Email Delivery.

Thank You @synox for this awesome Software.
