### ISSUE TITLE
Delay in Email showing

### ISSUE THREAD

**Issue by himsingh17** [synox/disposable-mailbox#23]
Hey synox,

There's something issue in Email Showing!.
I tested the working of script but the time taken in showing email on screen is too much.
It maybe an issue of refreshing code.

You can check test demo at www.viralhits.org/

Thank you

**Comment by synox** [comment]
Login to your imap account with a mail client to compare the time. It's usually a problem in the mail delivery.

**Comment by himsingh17** [comment]
@synox  Thanks for reply !! That was error in Godaddy hosting ! When I tried another hosting, it worked fine.
ps can you check your gitter please !
