### ISSUE TITLE
Tried. But didn't worked on a Ubuntu 16.04

### ISSUE THREAD

**Issue by parveenbhadoo** [synox/disposable-mailbox#24]
Need simple line to line commands to use it.
Please help with line to line commands needs to be used to install required like php and php imap extension

**Comment by synox** [comment]
I'm sorry I cant support you with Webserver installation. I recommend using a shared-hosting solution like https://www.godaddy.com/hosting/web-hosting or https://uberspace.de/

**Comment by parveenbhadoo** [comment]
But in Godaddy Shared Hosting what to fill here,
$config['imap']['url'] = '{example.com/imap/ssl}INBOX';

**Comment by parveenbhadoo** [comment]
I installed it at https://www.tricksbygoogle.com/mail/

imap settings
$config['imap']['url'] = '{tricksbygoogle.com}INBOX';
$config['imap']['username'] = "tricksbygoogle";
$config['imap']['password'] = "Katehra@1";

error is

{
  "data": "<br />\n<b>Fatal error</b>:  Uncaught exception 'PhpImap\\Exception' with message 'Connection error: Certificate failure for tricksbygoogle.com: Server name does not match certificate: /OU=Domain Control Validated/CN=*.prod.sin2.secureserver.net' in /home/tricksbygoogle/public_html/mail/backend-libs/php-imap/php-imap/src/PhpImap/Mailbox.php:67\nStack trace:\n#0 /home/tricksbygoogle/public_html/mail/backend-libs/php-imap/php-imap/src/PhpImap/Mailbox.php(58): PhpImap\\Mailbox-&gt;initImapStream()\n#1 /home/tricksbygoogle/public_html/mail/backend.php(32): PhpImap\\Mailbox-&gt;getImapStream()\n#2 /home/tricksbygoogle/public_html/mail/backend.php(161): print_emails('admin', 'admin@tricksbyg...')\n#3 {main}\n  thrown in <b>/home/tricksbygoogle/public_html/mail/backend-libs/php-imap/php-imap/src/PhpImap/Mailbox.php</b> on line <b>67</b><br />\n<br />\n<b>Notice</b>:  Unknown: Certificate failure for tricksbygoogle.com: Server name does not match certificate: /OU=Domain Control Validated/CN=*.prod.sin2.secureserver.net (errflg=2) in <b>Unknown</b> on line <b>0</b><br />\n",
  "status": 200,
  "config": {
    "method": "GET",
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "params": {
      "username": "admin"
    },
    "url": "./backend.php",
    "headers": {
      "Accept": "application/json, text/plain, */*"
    }
  },
  "statusText": "OK"
}

**Comment by synox** [comment]
for imap config you have to use the same as you use in your desktop imap client. try it first with thunderbird.

**Comment by parveenbhadoo** [comment]
Thanks @synox Sir, worked on TMD Hosting. https://www.pranavajagekar.com/#/admin

Awesome Project.

**Comment by synox** [comment]
great! 👍

**Comment by synox** [comment]
remember to subscribe for the gitter chat to get notified about updates.

**Comment by parveenbhadoo** [comment]
hi, check here https://www.pranavajagekar.com/#/admin
a single email shows 2 times everytime.
