### ISSUE TITLE
address blacklist

### ISSUE THREAD

**Issue by jongcs** [synox/disposable-mailbox#27]
Should have a address blacklist to reserve some address like admin@ administrator@ hostmaster@ postmaster@ webmaster@. Attackers can use these address to verify the domain ownership and get SSL certificate for the domain.

**Comment by synox** [comment]
oh good point!

**Comment by tricksbygooglecdn** [comment]
Exactly where is the file needs to be updated to blacklist usernames?

**Comment by HashHackerAds** [comment]
@synox Which file needs to be updated to blacklist usernames? and will blacklisted username when opened shows that it is blacklisted?

**Comment by synox** [comment]
blacklisted usernames will be forwarded to a random address. 

see https://github.com/synox/disposable-mailbox/blob/master/src/index.php#L167

**Comment by synox** [comment]
Update: I moved the list of blocked users to the config file. 

https://github.com/synox/disposable-mailbox/blob/master/src/config.sample.php#L32
