### ISSUE TITLE
Internal Server Error without entries in error_log

### ISSUE THREAD

**Issue by g1lby** [synox/disposable-mailbox#28]
Hi everyone,
I just installed disposable-mailbox on my Plesk-hostingserver (CentOS, nginx as caching server for apache2).
Unfortunately, I'm getting this error, when visiting the URL where I installed it:

![https://imgur.com/a/hIgVw](https://i.imgur.com/A3feBzH.png)

In my apache2 error_log there are no errors logged, which gives me a hard time debugging. I did install all the requirements as described in the readme.md.

**Comment by synox** [comment]
You have to configure php.ini to correctly log errors. The Problem is in the backend.

**Comment by g1lby** [comment]
Hi synox,
thanks for your very quick response and suggestion.
I noticed that display_errors was set to off in my php.ini. After turning this option on, I'm able to see the error.
The domain name in the SSL certificate for the domain where disposable-mailbox is installed, differs from the domain name in the SSL certificate for the mailserver.
So basically I'm running disposable-mailbox on domain1.com, which is secured by let's encrypt and I'm running the mailserver on the same machine (but with a different domain) with a let's encrypt certificate for mail.domain2.com (that's the mailserver name which all my customers are using, so I can't change that).
Do you have any suggestions how to solve this dilemma?
Cheers,
g1lby

**Comment by synox** [comment]
Seems that you don't have the correct root certificates installed. You can configure ssl in the imap url, or even disable ssl checks. see http://php.net/manual/en/function.imap-open.php

**Comment by g1lby** [comment]
Awesome, thanks!
I just edited line the line in config.php where ['imap'] ['url'] is configured and added "/novalidate-cert" to the end of the url.
Works like a charm :) 👍

**Comment by synox** [comment]
Is there something in docs we could improve, so that somebody else would find the solution faster?

**Comment by capsload** [comment]
Sorry guys for re-opening.

Im using zoho.com and i dont what to enter in that line?

$config['imap']['url'] = '';

can you give me a example?

**Comment by g1lby** [comment]
Hi capsload,
I don't know about zoho.com, but I can tell you what I entered in that line:

before: `$config['imap']['url'] = '{example.com/imap/ssl/}INBOX';` (that was giving me the error above)
after: `$config['imap']['url'] = '{example.com/imap/ssl/novalidate-cert}INBOX';` (that solved it for me)
