### ISSUE TITLE
Problem with fetching the JSON. (HTTP_ERROR). Status: 500 / SSL Problems

### ISSUE THREAD

**Issue by zaingithub** [synox/disposable-mailbox#3]
Hi, thank you very much for your source code, it is very simple to instal. i installed this code on my centos 7 server.

Everything is ok until i acessed the server, it saying "problem with fetching the JSON. (HTTP_ERROR). Status: 500"
Here the details :
Sorry, there was a problem.
There is a problem with fetching the JSON. (HTTP_ERROR). Status: 500
Make sure the backend works corrently using the developer tools of your web browser. 
Can you show me what kind of mistake of it? and how to solve it. 

if i am using a custom host email, etc domainku.com, how should i do with MX records etc?

Thanks.

**Comment by synox** [comment]
Try to access the backend directly and check the ouput. Also check the php-errorlog.

**Comment by zaingithub** [comment]
Hi, thank you for reply. I have checked the httpd error log, it says directory of config.php not found. and then i set the root directory to require_once the config.php.

To access the backend directly, it shown a blank display. the page isn’t working.
i try using this : /backend.php?action=get&username=zain

**Comment by zaingithub** [comment]
I am not sure how to setting up this : 

// setup imap connection
$config['imap']['host'] = "45.32.105.20";
$config['imap']['url'] = '{' . $config['imap']['host'] . '/imap/ssl}INBOX';
$config['imap']['username'] = "mypassword";
$config['imap']['password'] = "mypassword";

// email domain, usually different from imap hostname:
$config['mailHostname'] = "mydomain.com";

i am using VPS centos, with IP above. And want to use mailhostname mydomain.com

after seeing the error log : [Wed Nov 23 22:06:09.439340 2016] [:error] [pid 4327] [client 36.78.59.59:53583] PHP Fatal error:  Uncaught exception 'PhpImap\\Exception' with message 'Connection error: Can't connect to 45.32.105.20,993: Connection refused' in /var/www/html/backend-libs/php-imap/php-imap/src/PhpImap/Mailbox.php:67\nStack trace:\n#0 /var/www/html/backend-libs/php-imap/php-imap/src/PhpImap/Mailbox.php(58): PhpImap\\Mailbox->initImapStream()\n#1 /var/www/html/backend.php(63): PhpImap\\Mailbox->getImapStream()\n#2 /var/www/html/backend.php(43): search_mails('benagra@horemp3...', Object(PhpImap\\Mailbox))\n#3 /var/www/html/backend.php(117): print_inbox('benagra')\n#4 {main}\n  thrown in /var/www/html/backend-libs/php-imap/php-imap/src/PhpImap/Mailbox.php on line 67, referer: http://45.32.105.20/

**Comment by synox** [comment]
Please verify the imap settings using an imap client. Maybe you have to adjust the imap settings in the url, after the slash. E.g. Disable ssl or disable ssl verification. See the options here: http://php.net/manual/en/function.imap-open.php

Most probably you have to adjust the port and ssl type.

**Comment by flowcr** [comment]
Can you help me with this error  http://image.prntscr.com/image/6a3d2658757f4c5a87861532914eb651.png

**Comment by synox** [comment]
Just like the previous answer, check your settings in `config.php`. 
 
Please verify the imap settings using an imap client. Maybe you have to adjust the imap settings in the url, after the slash. E.g. Disable ssl or disable ssl verification. See the options here: http://php.net/manual/en/function.imap-open.php

Most probably you have to adjust the port and ssl type.

**Comment by flowcr** [comment]
Thank you problem solved
