### ISSUE TITLE
Problems with Homepage

### ISSUE THREAD

**Issue by HashHackerAds** [synox/disposable-mailbox#30]
Can you fix this file
https://github.com/wp-cdn-pbf/cdn.bhadoo.net/blob/master/frontend.template.php
running at https://beta.bhadoomail.com

Ads Doesn't loads sometimes and visitor counter shows error when the page refreshes automatically.
Can you tell me how to exclude the ads and counter out of auto refresh but show at the same place as they are.

check both for mobile and desktop

**Comment by HashHackerAds** [comment]
@synox Another Problem Found. 
Check here
https://bhadoomail.com/bhadoo.net/#/Support
Capital Letters doesn't effects retrieval of emails.
while in new version
https://beta.bhadoomail.com/?Support@bhadoo.net
and
https://beta.bhadoomail.com/?support@bhadoo.net

doesn't reads email if Capitals are in there.

**Comment by HashHackerAds** [comment]
Add One More Feature
One Click to Copy Current Email Address

`<script>
    function copyToClipboard(element) {
    var $temp = $("<input>");
    $("body").append($temp);
    $temp.val($(element).text()).select();
    document.execCommand("copy");
    $temp.remove();
    }
    </script>

<a role="button" class="btn btn-outline-primary" onclick="copyToClipboard('#p1')" >Copy Email</a>`

**Comment by HashHackerAds** [comment]
@synox 
add click to copy button feature please
here is code
https://github.com/wp-cdn-pbf/cdn.bhadoo.net/blob/master/code2copy.txt

**Comment by Spegeli** [comment]
i can confirm the capital letters issue.
the name should be converted always to lowercase.

**Comment by synox** [comment]
1) To avoid refreshing parts of the page: 
With the attribute "data-turbolinks-permanent" you can exclude a dom tree from beeing replaced. 
example: 
`<form id="header-form" data-turbolinks-permanent action="?" method="post">`

See https://github.com/turbolinks/turbolinks

2) In commited a version with strtolower. 

3) Copy button:  I like Spegeli's version. jQuery is opselete.

**Comment by synox** [comment]
Let me know if you have any other issue (create a ticket for each issue, or reopen this one)

**Comment by synox** [comment]
@HashHackerAds Can I link to https://bhadoomail.com as a demo site?

**Comment by HashHackerAds** [comment]
Ofcourse, Sir.
