### ISSUE TITLE
Check if email is HTML or TEXT

### ISSUE THREAD

**Issue by Spegeli** [synox/disposable-mailbox#34]
Don't know if it's possible to check (via the header) if a email is in HTML or Text format. 

Then we can display HTML direct as HTML and Text direct as Text as default.

**Comment by Spegeli** [comment]
Maybe this helps:

Content-Type: text/plain;
Content-Type: text/html;

**Comment by synox** [comment]
My idea was, that html in general is insecure and should only be used if the text view is not usable. What do you think?

Having HTML default if available would be easily possible.

**Comment by Spegeli** [comment]
I would prefer HTML as default when available.
But PlainText as default when available would be Ok too.

`if (PlainText) { showPlainText(); } else { showHTML(); }`

**Comment by synox** [comment]
or we could configure the default in config. ;-) So wo both win ;-)

**Comment by synox** [comment]
Still there is the related bug: https://github.com/synox/disposable-mailbox/issues/32

**Comment by synox** [comment]
@Spegeli please review the Pull-Request https://github.com/synox/disposable-mailbox/pull/35

**Comment by Spegeli** [comment]
@synox 

Here it seems working good: http://www.postfach2go.de/?ciokni69@postfach2go.de

But here is a email showen as plain but as you can see it contains css and is therefore a HTML Mail: http://www.postfach2go.de/?gudi@postfach2go.de

**Comment by synox** [comment]
the CSS is a problem in the mail, not the app. See source

	--_=_swift_v4_1515873062_aaefdc6e5f60382185f008826291549c_=_
	Content-Type: text/plain; charset=utf-8
	Content-Transfer-Encoding: quoted-printable


	Produktmuster | Tiger Balm                                                 =
	       #outlook a {                    padding: 0;                }        =
	        .ReadMsgBody {                    width: 100%;                }    =
	            .ExternalClass {                    width: 100%;               =

**Comment by synox** [comment]
Images are not loaded, you could change that in the first few lines of the template file.
