### ISSUE TITLE
Display a Specific Email Address

### ISSUE THREAD

**Issue by HashHackerAds** [synox/disposable-mailbox#36]
I want to know how can i make some page to display a specific email address.
Like if i open https://bhadoomail.com?new@bhadoo.net it shows this email but can be changed,
I want to display exactly this email on a specific page without allowing to change email address.
I want this to provide Gmail email accounts. (specific address that exists only)
or
Like multi domain if its possible to display a specific domains several email addresses on page to select one from.

**Comment by synox** [comment]
For this you have to change the template, and set static text instead of the form, or a static select field. 
Won't Support for general users.
