### ISSUE TITLE
How to Install to Heroku?

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [synox/disposable-mailbox#42]
Ref: 
https://stackoverflow.com/questions/43442212/check-imap-mail-with-heroku-app
https://devcenter.heroku.com/articles/php-support#activation

**Comment by synox** [comment]
Can you make a PR?

**Comment by ParveenBhadooOfficial** [comment]
I have added composer.json and composer.lock files, it gets deployed but something is still missing, i don't know about composer, but i tried to fix things.

anyone know composer can check this here

https://github.com/ParveenBhadooOfficial/bhadoomail

**Comment by ParveenBhadooOfficial** [comment]
Log:

-----> PHP app detected
-----> Bootstrapping...
-----> Installing platform packages...
       - php (7.2.1)
       - ext-imap (bundled with php)
       - apache (2.4.29)
       - nginx (1.8.1)
 !     WARNING: Your 'composer.lock' is not up to date with the latest
       changes in 'composer.json'. To ensure you are not getting stale
       dependencies, run 'composer update' on your machine and commit
       any changes to Git before pushing again.
-----> Installing dependencies...
       Composer version 1.6.2 2018-01-05 15:28:41
       Loading composer repositories with package information
       Installing dependencies from lock file
       Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
       Package operations: 3 installs, 0 updates, 0 removals
         - Installing php-imap/php-imap (2.0.3): Loading from cache
         - Installing gnugat/pronounceableword (2.0.0): Loading from cache
         - Installing ezyang/htmlpurifier (v4.9.3): Loading from cache
       Package gnugat/PronounceableWord is abandoned, you should avoid using it. No replacement was suggested.
       Generating optimized autoload files
-----> Preparing runtime environment...
       NOTICE: No Procfile, using 'web: heroku-php-apache2'.
-----> Checking for additional extensions to install...
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 15.4M
-----> Launching...
       Released v5
       https://test-mail-1.herokuapp.com/ deployed to Heroku

**Comment by ParveenBhadooOfficial** [comment]
Hi, @synox I have found a way for Heroku. Cannot make a PR, because don't know how to merge my way directly here. but you can check and update it yourself from here
https://github.com/hashhackers/Mail.BhadooMail.com
