### ISSUE TITLE
Email from Google, Script Violates PII Policy.

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [synox/disposable-mailbox#43]
Hi, i need to know how i can hide the ?username@domain.com from the url.
Because it violates the google's policy. Can anyone help me avoid Email Address showing in address bar.

Here is Google's Email

Publisher ID: ca-pub-xxxxxxxxxxxxxxxxxxxxxx

Dear Publisher,

It has come to our attention that you are passing personally identifiable information (PII) to Google through your use of one or more of Google's advertising products -- AdSense, DoubleClick for Publishers, and/or DoubleClick Ad Exchange.

Our systems have detected information, including email addresses and/or passwords, being passed from the ad requests attached to this email.

Our contracts and policies prohibit information being passed to us that we could recognize as PII. By sending us such information, you are in breach of those terms. We take this issue very seriously, and ask that you give it your immediate attention. We require that you fix the issue within 30 days.

We ask that you take the following steps to correct the problem:

Submit this form to update us on your progress. If you don’t submit the form within the next 14 days, we will place a payment hold on your monetization account (AdSense and AdX). Be sure to enter your publisher ID exactly as it is shown at the top of this notification.
Review the example ad requests in the attached file. Use this information to start your investigation.
Refer to our help center for additional guidance.
Please be advised that all future communications regarding this issue will occur via email; no notifications will appear inside any ad serving products.

Regards,

The Google Publisher Policy Team

Attached File Contained this

Publisher ID: ca-pub-xxxxxxxxxxxxxxxxxxxxxxxxx

Number of domains: 1

Domain: bhadoomail.com has 1 unique url(s).

URL group: bhadoomail.com/
Found 6062 time(s) or 1 of the total records
URL sample: https://bhadoomail.com/?redacted@example.com
Record sample: GET /pagead/ads?client=ca-pub-5435553179213419&output=html&adk=1812271804&adf=3025194257&lmt=1517227659&loeid=38893312&plat=2%3A1024%2C16%3A8388608&format=0x0&url=https%3A%2F%2Fbhadoomail.com%2F%3Fredacted%40example.com&ea=0&flash=0&pra=5&wgl=1&dt=1517227659698&bpp=98&bdt=286&fdt=117&idt=142&shv=r20180122&cbv=r20170110&saldr=aa&correlator=2369061920204&frm=20&ga_vid=*&ga_sid=*&ga_hid=*&ga_fc=0&pv=2&iag=3&icsg=2&nhd=1&dssz=2&mdo=0&mso=0&u_tz=330&u_his=12&u_java=0&u_h=640&u_w=360&u_ah=640&u_aw=360&u_cd=24&u_nplug=0&u_nmime=0&adx=0&ady=0&biw=360&bih=566&abxe=1&scr_x=0&scr_y=0&eid=21061122%2C38893302%2C62710011%2C62710014%2C191880502%2C370204013&oid=3&ref=https%3A%2F%2Fbhadoomail.com%2F%3Fredacted%40example.com&rx=0&eae=2&fc=920&brdim=0%2C0%2C0%2C0%2C360%2C0%2C360%2C566%2C360%2C566&vis=1&rsz=%7C%7Cnr%7C&abl=CS&ppjl=f&fu=16&bc=1&osw_key=2854398722&ifi=0&dtd=359 HTTP/1.1
Most recent time: 2018-02-04 07:57:36 UTC

**Comment by synox** [comment]
That's interesting, Google is actually right. The page should not leak information about the user oder email address to the adds provider. 

Having the email in the query is actually an important feature, so you can bookmark it and come back to it (common practise for trash mail providers). 

Possible ways to address this issue: 

1) don't use adds 

2) create a page example.com/adds with the adds, then load them with an <iframe>. This should mask to origin. 

3) Not Usable: Save the email address as Cookie, or send the forms with POST. Both have the problem, that you can not bookmark the page. Moreover for Cookies, you can only save the latest address. 

I would advise to try variant 2.

**Comment by ParveenBhadooOfficial** [comment]
2nd is again against Google Policies to render content.
3rd creates bookmarking problem.
Going for 1st one. No Ads Served from Now on BhadooMail.com
