### ISSUE TITLE
Show HTML / Show Text

### ISSUE THREAD

**Issue by coralrb** [synox/disposable-mailbox#45]
Great script! 

I noticed however that when you click "Show HTML" to read your email, it is automatically set back to "Show Text" when the page auto refreshes. This makes it so you need to keep clicking "Show HTML"... Is there a way to have the "Show HTML" or "Show Text" be remembered so it persists through page refreshes?

**Comment by synox** [comment]
Please update to the newest version, the buttons were removed...
