### ISSUE TITLE
How can i remove this but still keep the bookmarking option?

### ISSUE THREAD

**Issue by HashHackerAds** [synox/disposable-mailbox#46]
Can we do like in the older version
https://bhadoomail.com/#/emails

new version
https://bhadoomail.com/?emails@bhadoo.net

can be
https://bhadoomail.com/?emails&bhadoo.net
i.e. username&domain like that options? can be bookmarked, cannot Send PII requests to Google.

**Comment by synox** [comment]
It still leakes information, you can't have both. 

Maybe check what other sites do..

**Comment by ParveenBhadooOfficial** [comment]
Can you tell what needs to be changed to remove the https://mail.bhadoomail.com/inbox/?bump67@dotmail.cf email from here, ignoring the bookmarking.

**Comment by synox** [comment]
you would save a cookie with email address.
