### ISSUE TITLE
Aufrufen einer ImapClient Funktion aus dem Template?

### ISSUE THREAD

**Issue by Spegeli** [synox/disposable-mailbox#49]
Servus,
hab gerade die neusten Änderungen übernommen und hat soweit alles Funktioniert, nur bei einer Funktion hab ich ein kleines Problem.
Ich habe eine reply.template.php (ein klon des normalen fronted  templates welche ich für die antwort funktion umgemodded hab), dort habe ich folgende funktion:
```

$mailSent = mail($mailToAddress, $mailSubject, $mailText, $mailHeader);
if($mailSent == TRUE)
    $imapClient->set_answered_flag($reply_email->id, $user);
```

und in der imap_client.php habe ich folgenden code:

```
    public function set_answered_flag(int $mailid, User $user) {
        if ($this->load_one_email($mailid, $user) !== null)
            $this->mailbox->setFlag(array($mailid), '\\ANSWERED');   
    }
```

allerdings hat er seit der Integration der letzten Änderungen wohl ein Problem auf diese Funktion innerhalb der $imapClient zuzugreifen.

Hast du da zufällig einen Typ wie ich die Funktion aufrufen kann aus dem template herraus?

**Comment by synox** [comment]
Spontan würde ich sagen: wird imap connection ordentlich geschlossen? Es hat neu ein paar exit/die Aufrufe mehr...

**Comment by Spegeli** [comment]
Es geht doch darum wie ich die ImapClient class aus dem Template aus ausrufen kann.
Selbst wenn ich in der imap_client.php in der ImapClient class folgenden Code habe:

```
    public function set_answered_flag() {
        return null;  
    }
```

und im Template folgenden Code benutze:

```
        if($mailSent == TRUE)
            $imapClient->set_answered_flag();
```

Spuckt er nix aus bzw. verursacht nen break im code.

**Comment by synox** [comment]
Weiss nicht, da müsste ich den ganzen Code sehen...

**Comment by Spegeli** [comment]
Den ganzen Code hast du doch ;-)

Stell dir einfach vor du willst: 
`echo $imapClient->set_answered_flag();`
im frontend.template.php einbauen so das es dann dort auf
```
    public function set_answered_flag() {
        return 0;  
    }
```
zugreift, welches sich in der imap_client.php befindet.

**Comment by synox** [comment]
.. ich probiere das bei Gelegenheit mal. 

Mir fällt noch auf: Aus dem Template darfst du keine mutierenden Funktionen aufrufen, sondern dein $imapClient->set_answered_flag() muss im Controller aufgerufen werden! (Sonst würde es z.B. beim JSON-API nicht funktionieren. https://github.com/synox/disposable-mailbox/blob/master/src/json-api.php#L13)

See also http://www.phptherightway.com/pages/Design-Patterns.html

**Comment by synox** [comment]
closing after inactivity
