### ISSUE TITLE
Delete Option ?!

### ISSUE THREAD

**Issue by Spegeli** [synox/disposable-mailbox#5]
First i have to say thx for this amazing script.
It's simple but it does what it should ;-)

The only thing i'm missing is a option to delete a message.
Maybe its possible for you to add this?!

**Comment by synox** [comment]
Pull request welcome. It's easy, look at the example here: https://github.com/synox/disposable-email-imap/blob/master/index.php#L77

**Comment by Spegeli** [comment]
index.html
```
                        <div class="col-sm-12 email-summary">{{mail.subject}}
                        <form class="form-inline float-xs-right">
                            <button ng-click="$ctrl.deleteEmail(mail.id)" type="button" class="btn btn-outline-primary">Delete {{mail.id}}</button>
                        </form>
                        </div>
```
backend.php
`/**
 * deletes messages on request.
 */
function delete_message($id) {
    global $mailbox;
    
    $mailbox->deleteMail($id);
    $mailbox->expungeDeletedMails();
}`

**Comment by synox** [comment]
Please fork this repo and create a pull request (https://guides.github.com/activities/forking/).  This makes it much easier to discuss and allows me to run the code.

**Comment by Spegeli** [comment]
Sorry i dont want to fork it ;-)

**Comment by synox** [comment]
Why not fork? It's free and you delete it afterwards. That's how github works you know. ;-)

**Comment by synox** [comment]
Thanks anyway for the input. I improved it a bit and pushed to master branch.

**Comment by synox** [comment]
#2  must also be fixed here.
