### ISSUE TITLE
blank page after install dispoable mailbox

### ISSUE THREAD

**Issue by WangCharlie** [synox/disposable-mailbox#50]
Here is the snapshot. please take a look

![image](https://user-images.githubusercontent.com/6106454/37327290-b1ec2f2e-26d0-11e8-8d53-78d707e41531.png)

**Comment by synox** [comment]
See https://github.com/synox/disposable-mailbox/blob/master/README.md about installation.

**Comment by synox** [comment]
open it in your browser, check your php error log for messages.

**Comment by gtsatsis** [comment]
The error that they are probably receiving is: `PHP Parse error:  syntax error, unexpected '?' in /src/imap_client.php on line 49`

Currently going through this, and removing all of the question marks apparently allows for booting the page up; Currently waiting for MX propagation to verify if this fix works

**Comment by gtsatsis** [comment]
Yep, it appears that removing all question marks (invalidly placed ones, at least) from imap_client.php will fix it!

**Comment by synox** [comment]
Make sure you have php 7.2 installed.

**Comment by gtsatsis** [comment]
PHP 7.2 is installed and enabled in my configuration.

2018-03-17 10:15 GMT+02:00 Aravindo Wingeier <notifications@github.com>:

**Comment by synox** [comment]
Ok thats weird. Please tell me which version (commit) you use, on which apache and php version. I'll try to reproduce it   .

**Comment by gtsatsis** [comment]
Latest (Currently on phone so I can't grab the commit), Apache 2.4 and PHP
7.2

2018-03-17 18:47 GMT+02:00 Aravindo Wingeier <notifications@github.com>:

**Comment by synox** [comment]
Ok. Nullable types are new feature of php 7.1. See http://php.net/manual/en/migration71.new-features.php

Users of php 5.x would get the error "PHP Parse error:  syntax error, unexpected ':', expecting '{' in - on line "

Please make sure you are using the latest version of php. 

run `php-7.1/bin/php`, then paste the following and press ctrl-d. 

	<?php
	function testReturn(): ?string
	{
	    return 'elePHPant';
	}

It should print nothing. Others versions of php do. 

This leads to the question: Is it safe to assume everybody gets the new php versions?  7.2 was released on 30 Nov 2017.

**Comment by synox** [comment]
if o

**Comment by ParveenBhadooOfficial** [comment]
in Godaddy the new code of index.php file says. 


ERROR! The php version isn't high enough, you need at least 7.2 to run this application! But you have: 7.1.14


also https://play.google.com/store/apps/details?id=com.parveenbhadoo.bhadoomail&utm_source=BhadooMail_Com&utm_campaign=Bhadoo_Industries_Open_Source&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1
On Play Store Now. No Ads. :)
