### ISSUE TITLE
Lots of Emails Overloads the Page, Add the Show and Hide Button.

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [synox/disposable-mailbox#54]
Can you please add the old show hide button for each mail. It should show the title not the entire email. It is overloading the page because of too many mails on a single page open.

**Comment by ParveenBhadooOfficial** [comment]
Yes, that one. or maybe you can fix it like on opening page it shows title and details of emails. on clicking it should show full email.

**Comment by synox** [comment]
Hmm like this? https://maildrop.cc/inbox/asdf

If you limit it to see only one mail at a time should be doable.

**Comment by ParveenBhadooOfficial** [comment]
Yeah, But i don't know how to do it.

**Comment by bertlio** [comment]
Hello there! This feature would be really welcomed and will be easier to manage received email... Thank you for considering it!

**Comment by synox** [comment]
Released https://github.com/synox/disposable-mailbox/releases

**Comment by synox** [comment]
Please see discussion #58 about how to further improve the layout.
