### ISSUE TITLE
Make Email Adresse check case-insensitiv

### ISSUE THREAD

**Issue by Spegeli** [synox/disposable-mailbox#6]
As the title say, currently its case-sensitiv.
So when i send Emails to maxmuster@mydomain.de and i check via the Website for Maxmuster@mydomain.de it not found the Emails.

Would be better to make it case-insensitiv.
So it no matters in i search for maxmuster, MaxMuster or MaXmUsTeR.

**Comment by Spegeli** [comment]
Would be better to make it case-insensitiv.
So it no matters in i search for maxmuster, MaxMuster or MaXmUsTeR.

**Comment by Spegeli** [comment]
Ok it seems that the email adresses always lower case so it one solution be to change in the backend.php the following:

`$name = strtolower(clean_name($username));`

**Comment by Spegeli** [comment]
I found a better solution:
In the index.html change:
```
                    <input ng-model="$ctrl.inputFieldUsername"
                           placeholder="username"
                           type="text" class="form-control"/>
```
to
```
                    <input ng-model="$ctrl.inputFieldUsername"
                           placeholder="username"
                           type="text" class="form-control"
                           ng-change="$ctrl.inputFieldUsername=$ctrl.inputFieldUsername.toLowerCase();" />
```
this will auto convert the input in the Username Field to lowercase ;-)

**Comment by synox** [comment]
fixed.
