### ISSUE TITLE
index.php not loading correctly

### ISSUE THREAD

**Issue by dave90dave** [synox/disposable-mailbox#70]
Hello, 
I tried to install the disposable mail system and followed the instructions on the github page, the details if've filled in are all correct but when loading the index.php it only shows a $_GET link in the url bar with the generated email box. But the page stays blank. Is there something that has to be changed, my server meets the requirements.

regards
Dave

**Comment by joshp23** [comment]
Consider providing more information, such as system setup, browser, log detail, etc.

**Comment by dave90dave** [comment]
Hello Josh,
I got it running on PHP 7.2
I tested the Imap function and it says it is installed
PHP errors are enabled, but there are no errors shown on the website.
Browser: Firefox 62.0.3 (tried chromium too)
My website: www.davehulst.nl
Should there be a log somewhere around?

**Comment by joshp23** [comment]
You can check the webserver's log file. With apache it's in /var/log

**Comment by joshp23** [comment]
You might consider turning on the developer console in FF and see if there is anything there.

**Comment by mernoid** [comment]
I have exactly the same issue. 
I am using SIteground with Imap and everything. Domain: https://www.distempmail.com/

There are no relevant errors in the error log or in the console.

**Comment by dave90dave** [comment]
In my error log are just 2 lines saying that the config.php was not found, and thats right because i didn't set my config file then. That is my full log

**Comment by joshp23** [comment]
Seems like you should set your [config.php](https://github.com/synox/disposable-mailbox#installation)... please don't forget to close this issue.

**Comment by synox** [comment]
@joshp23 thanks for the support!

**Comment by synox** [comment]
#71 should improve this

**Comment by dave90dave** [comment]
I'm sorry, but this was not the problem, i already have set this config, moved it to /private directory. And I changed the index/json api too. But even then it doesn't work. I reinstalled it right now and problem is still not solved. 

> 
> 
> In my error log are just 2 lines saying that the config.php was not found, and thats right because i didn't set my config file then. That is my full log

**Comment by joshp23** [comment]
check your permissions on config.php, and make sure the path settings are correct in index/json

**Comment by dave90dave** [comment]
Thats very stupid from me, I didn't get any errors because the ini_set & error reporting function where commented out. Now I get the following error message:
Fatal error: Uncaught PhpImap\Exception: Connection error: Certificate failure for imap.transip.email: self signed certificate in certificate chain: /C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root in /www/backend-libs/php-imap/php-imap/src/PhpImap/Mailbox.php:67 Stack trace: #0 /www/backend-libs/php-imap/php-imap/src/PhpImap/Mailbox.php(58): PhpImap\Mailbox->initImapStream() #1 /www/imap_client.php(19): PhpImap\Mailbox->getImapStream() #2 /www/controller.php(159): ImapClient->get_emails(Object(User)) #3 /www/index.php(22): DisplayEmailsController->invoke(Object(ImapClient)) #4 {main} thrown in /www/backend-libs/php-imap/php-imap/src/PhpImap/Mailbox.php on line 67 Notice: Unknown: Certificate failure for imap.transip.email: self signed certificate in certificate chain: /C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root (errflg=2) in Unknown on line 0 

It looks like the SSL certificate is self signed, do I need to add a php mail tag or something to let the php application connect to the imap server with self signed certificate?

**Comment by joshp23** [comment]
Why not just use letsencrypt certificates?

**Comment by dave90dave** [comment]
> 
> 
> Why not just use letsencrypt certificates?

I was using Lets encrypt, but since I protect my domain with cloudflare the cloudflare certificate will be used :/

**Comment by Mosrod** [comment]
@dave90dave Did you mean ('{mail.domain.com:143/ssl/novalidate-cert}?

**Comment by Mosrod** [comment]
This issue showed up as a 500 Error for me
