### ISSUE TITLE
Add option to disable third party cdn's

### ISSUE THREAD

**Issue by Perflyst** [synox/disposable-mailbox#80]
I wanna selfhost this project because it is very nice and you dont need to relay on other disposable mailboxes online which may sell your data.
The issue I see here you contact a lot third party cdn's. Can you download the css/js files into the project or add an option to disable third party?

**Comment by synox** [comment]
good point. you can make a pull request if you like.

**Comment by synox** [comment]
I just tested the commit, some files can not be found.. 
GET /assets/fontawesome/webfonts/fa-solid-900.woff2 net::ERR_ABORTED 404 (Not Found)
2?winsouct87@dubgo.com:1 
GET/assets/fontawesome/webfonts/fa-solid-900.woff net::ERR_ABORTED 404 (Not Found)

**Comment by synox** [comment]
resolved
