### ISSUE TITLE
Any Way to add a loading icon or something while page reloads

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [synox/disposable-mailbox#86]
On site when we create new random inbox it should a loading or refreshing page. How can we add it to enhance user experience.

Something like in gmail, when we open gmail it shows logo while loading contents behind the wall.

**Comment by synox** [comment]
IMO, you should make the app faster, not add explanation why it is slow. 
Try a caching nginx or service worker cache.

**Comment by ParveenBhadooOfficial** [comment]
I have used jsdelivr for static files. I can add a service worker. but still sometimes, it keeps processing. I still couldn't found any errors. But I will check how to add caching and more to it. It will take time as I am just a beginner.

**Comment by ParveenBhadooOfficial** [comment]
I have added a service worker. on https://staging.bhadoomail.com

**Comment by ParveenBhadooOfficial** [comment]
Should we implement PWA in project as in https://staging.bhadoomail.com
