### ISSUE TITLE
How to Create Pure Disposable Email Address for Limited Time

### ISSUE THREAD

**Issue by vishal1714** [synox/disposable-mailbox#91]
Hello,

Can we make Disposable Email Address for limited time like 10 min or 15 min and after use.
mailbox get Destroyed so no one will use that mailbox again. This is very good Idea. This project is very Impressive but any one can access other user's mailbox and after use mailbox never get destroyed.

How to solve this problem ?

**Comment by synox** [comment]
I recommend using https://burner.kiwi/
it is also Open source and very modern and fast.
