### ISSUE TITLE
How to hide Email Address from URL 

### ISSUE THREAD

**Issue by vishal1714** [synox/disposable-mailbox#92]
For more secure use i implement 2 Disposable Email Service in same hosting

www.xxxxxx.com/inbox/ --> It is for Signup Users (They can make there own custom email ids)
www.xxxxxx.com/mailbox/ --> It is any User (They can get random email Address)

but to make 2nd mailbox i have to hide the URL email address eg.
http://www.xxxxx.com/mailbox/?ols68@qcazvy.tk

how to hide ?ols68@qcazvy.tk this part from url.

I know I have to use POST method but i have try but i did not get any success kindly share code if you do it

**Comment by synox** [comment]
You would have to use cookies, and use the cookie instead of the url parameter. Instead you could use https://github.com/haydenwoodhead/burner.kiwi which does this perfectly.
